# Production Docker Compose Override
version: '3.8'

services:
  backend:
    environment:
      - PYTHONOPTIMIZE=1
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  analytics:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  premium:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      target: production
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
