# VibeAI Railway Deployment Configuration

services:
  backend:
    source: .
    dockerfile: Dockerfile
    healthcheck: /api/health
    environment:
      PORT: 8000
      PYTHONPATH: /app
    variables:
      SERPER_API_KEY: ${{SERPER_API_KEY}}
      GEMINI_API_KEY: ${{GEMINI_API_KEY}}
      YOUTUBE_API_KEY: ${{YOUTUBE_API_KEY}}
      RESPONSE_TIMEOUT: 120

  analytics:
    source: .
    dockerfile: Dockerfile.streamlit
    healthcheck: /_stcore/health
    environment:
      PORT: 8501
      BACKEND_URL: ${{backend.RAILWAY_PUBLIC_DOMAIN}}
    variables:
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0

  premium:
    source: .
    dockerfile: Dockerfile.streamlit-premium
    healthcheck: /_stcore/health
    environment:
      PORT: 8502
      BACKEND_URL: ${{backend.RAILWAY_PUBLIC_DOMAIN}}
    variables:
      STREAMLIT_SERVER_PORT: 8502
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0

  frontend:
    source: ./web
    dockerfile: Dockerfile.frontend
    healthcheck: /
    environment:
      PORT: 5173
      VITE_API_URL: ${{backend.RAILWAY_PUBLIC_DOMAIN}}
      VITE_ANALYTICS_URL: ${{analytics.RAILWAY_PUBLIC_DOMAIN}}
      VITE_PREMIUM_URL: ${{premium.RAILWAY_PUBLIC_DOMAIN}}
