services:
  # VibeAI NUCLEAR OPTION - Pure Python HTTP Server (ZERO Dependencies)
  - type: web
    name: vibeai-nuclear-option
    env: python
    buildCommand: |
      echo "==============================================="
      echo "NUCLEAR OPTION: NO DEPENDENCIES TO INSTALL"
      echo "Using only Python standard library"
      echo "==============================================="
    startCommand: python3 pure_http_server.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    autoDeploy: true
