services:
  # VibeAI Nuclear Option - Pure Python HTTP Server
  - type: web
    name: vibeai-platform
    env: python
    buildCommand: echo "No build dependencies needed - using pure Python"
    startCommand: python pure_http_server.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
