services:
  # VibeAI Complete Platform - All Features Integrated
  - type: web
    name: vibeai-complete-platform
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements-complete.txt
    startCommand: python start_complete.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: RESPONSE_TIMEOUT
        value: "30"
      - key: MAX_SEARCH_RESULTS
        value: "5"
      - key: SEARCH_TIMEOUT
        value: "10"
    healthCheckPath: /health
    autoDeploy: true
