services:
  # Main VibeAI Backend API + Embedded Frontend  
  - type: web
    name: vibeai-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT --log-level info
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: RESPONSE_TIMEOUT
        value: "30"
      - key: MAX_SEARCH_RESULTS
        value: "5"
      - key: SEARCH_TIMEOUT
        value: "10"
    healthCheckPath: /api/health
    autoDeploy: true
    
  # React Frontend (Advanced UI)
  - type: web
    name: vibeai-frontend
    env: node
    buildCommand: cd web && npm install && npm run build
    startCommand: cd web && npm run serve
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: vibeai-backend
          property: host
    autoDeploy: true
    
  # Streamlit Analytics Dashboard
  - type: web
    name: vibeai-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run analytics_dashboard.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
    autoDeploy: true
    
  # Premium Analytics Dashboard
  - type: web
    name: vibeai-premium
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run premium_analytics.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
    autoDeploy: true
