services:
  # Main VibeAI Backend API
  - type: web
    name: vibeai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: RESPONSE_TIMEOUT
        value: "30"
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /api/health
    autoDeploy: true
    
  # Streamlit Analytics Dashboard
  - type: web
    name: vibeai-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run analytics_dashboard.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
    autoDeploy: true
    
  # Premium Analytics Dashboard
  - type: web
    name: vibeai-premium
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run premium_analytics.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
    autoDeploy: true
