services:
  # VibeAI ULTRA NUCLEAR - Force Override All Auto-Detection
  - type: web
    name: vibeai-ultra-nuclear
    env: python
    buildCommand: |
      echo "🔥 ULTRA NUCLEAR OPTION ACTIVATED 🔥"
      echo "Forcing Render to ignore ALL auto-detection"
      echo "Creating empty requirements file to satisfy Render"
      touch requirements.txt
      echo "# Nuclear option - no dependencies" > requirements.txt
      echo "ZERO external dependencies - pure Python only"
      echo "Build completed successfully with nuclear option"
    startCommand: python3 pure_http_server.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    autoDeploy: true
