services:
  # VibeAI Ultra-Simple Platform - Bypass Python 3.13 Issues
  - type: web
    name: vibeai-platform
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install --only-binary=all --no-build-isolation fastapi uvicorn pydantic
      python -m pip install --only-binary=all requests python-dotenv
      python -c "import fastapi, uvicorn, pydantic, requests; print('Core dependencies verified')"
    startCommand: python start_ultra_simple.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
