services:
  # VibeAI Complete Platform - All Features Integrated
  - type: web
    name: vibeai-complete-platform
    env: python
    buildCommand: |
      pip install --upgrade pip
      ls -la
      if [ -f "requirements-complete.txt" ]; then
        echo "Found requirements-complete.txt, installing..."
        pip install -r requirements-complete.txt
      elif [ -f "requirements-production.txt" ]; then
        echo "Fallback to requirements-production.txt..."
        pip install -r requirements-production.txt
      else
        echo "Installing minimal requirements..."
        pip install fastapi uvicorn google-generativeai requests python-dotenv pandas numpy
      fi
    startCommand: |
      if [ -f "start_robust.py" ]; then
        python start_robust.py
      elif [ -f "start_complete.py" ]; then
        python start_complete.py
      else
        python -m uvicorn main_complete:app --host 0.0.0.0 --port $PORT
      fi
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: RESPONSE_TIMEOUT
        value: "30"
      - key: MAX_SEARCH_RESULTS
        value: "5"
      - key: SEARCH_TIMEOUT
        value: "10"
    healthCheckPath: /health
    autoDeploy: true
