version: '3.8'

services:
  # Main FastAPI Backend + Embedded Frontend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - RESPONSE_TIMEOUT=30
      - MAX_SEARCH_RESULTS=5
      - SEARCH_TIMEOUT=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend (Advanced UI)
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  # Streamlit Analytics Dashboard
  analytics:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped

  # Premium Analytics Dashboard
  premium:
    build:
      context: .
      dockerfile: Dockerfile.streamlit-premium
    ports:
      - "8502:8502"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped

  # Nginx Reverse Proxy (Single Entry Point)
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - analytics
      - premium
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
